version: '2'
services:
    skilltracker-app:
        image: skilltracker
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://skilltracker-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=skilltracker
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    skilltracker-mongodb:
        extends:
            file: mongodb.yml
            service: skilltracker-mongodb
